INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (1, 'El gran Gatsby', 'F. Scott Fitzgerald', 'Ficción', 'Scribner','2','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (2, '1984', 'George Orwell', 'Ciencia ficción', 'Debolsillo','1','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (3, 'Orgullo y prejuicio', 'Jane Austen', 'Romance', 'Alba Editorial','2','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (4, 'Moby-Dick', 'Herman Melville', 'Aventura', 'Penguin Clásicos','4','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (5, 'El guardián entre el centeno', 'J.D. Salinger', 'Bildungsroman', 'Alianza Editorial','1','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (6, 'Al faro', 'Virginia Woolf', 'Ficción modernista', 'Ediciones Cátedra','1','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (7, 'Un mundo feliz', 'Aldous Huxley', 'Ciencia ficción', 'Debolsillo','2','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (8, 'Crimen y castigo', 'Fiódor Dostoievski', 'Ficción psicológica', 'Debolsillo','3','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (9, 'Jane Eyre', 'Charlotte Brontë', 'Gótico', 'Alba Editorial','2','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (10, 'El señor de los anillos', 'J.R.R. Tolkien', 'Fantasía', 'Minotauro','12','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (11, 'Cien años de soledad', 'Gabriel García Márquez', 'Realismo mágico', 'Cien años de soledad','5','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (12, 'El retrato de Dorian Gray', 'Oscar Wilde', 'Ficción gótica', 'Debolsillo','2','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (13, 'La sombra del viento', 'Carlos Ruiz Zafón', 'Novela gótica', 'Planeta','2','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (14, 'El principito', 'Antoine de Saint-Exupéry', 'Fábula', 'Salamandra','4','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (15, 'El extranjero', 'Albert Camus', 'Ficción filosófica', 'Alianza Editorial','1','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (16, 'Los hermanos Karamázov', 'Fiódor Dostoievski', 'Ficción filosófica', 'Debolsillo','1','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (17, 'El amor en los tiempos del cólera', 'Gabriel García Márquez', 'Realismo mágico', 'Debolsillo','2','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (18, 'Fahrenheit 451', 'Ray Bradbury', 'Ciencia ficción', 'Debolsillo','1','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (19, 'Los pilares de la tierra', 'Ken Follett', 'Novela histórica', 'Penguin Random House Grupo Editorial','5','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (20, 'El ruido y la furia', 'William Faulkner', 'Ficción', 'Debolsillo','2','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (21, 'Cumbres borrascosas', 'Emily Brontë', 'Gótico', 'Alianza Editorial','3','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (22, 'La insoportable levedad del ser', 'Milan Kundera', 'Ficción filosófica', 'Tusquets Editores','1','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (23, 'En busca del tiempo perdido', 'Marcel Proust', 'Ficción modernista', 'Alianza Editorial','3','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (24, 'El extranjero', 'Albert Camus', 'Ficción filosófica', 'Alianza Editorial','1','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (25, 'Matar a un ruiseñor', 'Harper Lee', 'Ficción', 'Grijalbo','4','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (26, 'Ulises', 'James Joyce', 'Ficción modernista', 'Debolsillo','3','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (27, 'La ciudad y los perros', 'Mario Vargas Llosa', 'Novela', 'Editorial Seix Barral','3','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (28, 'Cien años de soledad', 'Gabriel García Márquez', 'Realismo mágico', 'Cien años de soledad','5','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (29, 'Crónica de una muerte anunciada', 'Gabriel García Márquez', 'Realismo mágico', 'Debolsillo','3','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (30, 'Don Quijote de la Mancha', 'Miguel de Cervantes Saavedra', 'Novela de caballerías', 'Debolsillo','6','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (31, 'Crimen y castigo', 'Fiódor Dostoievski', 'Ficción psicológica', 'Debolsillo','1','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (32, 'El retrato de Dorian Gray', 'Oscar Wilde', 'Ficción gótica', 'Debolsillo','5','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (33, 'Pedro Páramo', 'Juan Rulfo', 'Realismo mágico', 'Fondo de Cultura Económica','2','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (34, 'Los miserables', 'Victor Hugo', 'Novela histórica', 'Editorial Losada','5','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (35, 'El túnel', 'Ernesto Sabato', 'Ficción', 'Seix Barral','7','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (36, 'El nombre de la rosa', 'Umberto Eco', 'Novela histórica', 'Lumen','4','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (37, 'Crónica de una muerte anunciada', 'Gabriel García Márquez', 'Realismo mágico', 'Debolsillo','1','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (38, 'La insoportable levedad del ser', 'Milan Kundera', 'Ficción filosófica', 'Tusquets Editores','1','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (39, 'El ruido y la furia', 'William Faulkner', 'Ficción', 'Debolsillo','1','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (40, 'Los pilares de la tierra', 'Ken Follett', 'Novela histórica', 'Penguin Random House Grupo Editorial','5','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (41, 'Matar a un ruiseñor', 'Harper Lee', 'Ficción', 'Grijalbo','5','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (42, 'La ciudad y los perros', 'Mario Vargas Llosa', 'Novela', 'Editorial Seix Barral','2','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (43, 'La insoportable levedad del ser', 'Milan Kundera', 'Ficción filosófica', 'Tusquets Editores','1','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (44, 'Matar a un ruiseñor', 'Harper Lee', 'Ficción', 'Grijalbo','3','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (45, 'Cien años de soledad', 'Gabriel García Márquez', 'Realismo mágico', 'Cien años de soledad','3','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (46, 'El extranjero', 'Albert Camus', 'Ficción filosófica', 'Alianza Editorial','3','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (47, 'El principito', 'Antoine de Saint-Exupéry', 'Fábula', 'Salamandra','4','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (48, 'El gran Gatsby', 'F. Scott Fitzgerald', 'Ficción', 'Scribner','3','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (49, 'Los miserables', 'Victor Hugo', 'Novela histórica', 'Editorial Losada','4','');
INSERT INTO libros (id, titulo, autor, genero, editorial, numero_ejemplares, foto) VALUES (50, 'El túnel', 'Ernesto Sabato', 'Ficción', 'Seix Barral','3','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (1, 'Juan', 'Gómez', 'juan.gomez@example.com', '678901234', '2023-07-01','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (2, 'María', 'López', 'maria.lopez@example.com', '678912345', '2023-07-02','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (3, 'Carlos', 'Rodríguez', 'carlos.rodriguez@example.com', '678923456', '2023-07-03','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (4, 'Ana', 'Martínez', 'ana.martinez@example.com', '678934567', '2023-07-04','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (5, 'Pedro', 'Hernández', 'pedro.hernandez@example.com', '678945678', '2023-07-05','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (6, 'Laura', 'García', 'laura.garcia@example.com', '678956789', '2023-07-06','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (7, 'José', 'Fernández', 'jose.fernandez@example.com', '678967890', '2023-07-07','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (8, 'Marta', 'Pérez', 'marta.perez@example.com', '678978901', '2023-07-08','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (9, 'Jorge', 'Díaz', 'jorge.diaz@example.com', '678989012', '2023-07-09','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (10, 'Lucía', 'Ortega', 'lucia.ortega@example.com', '678900123', '2023-07-10','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (11, 'Roberto', 'Ramos', 'roberto.ramos@example.com', '678911234', '2023-07-11','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (12, 'Isabel', 'Molina', 'isabel.molina@example.com', '678922345', '2023-07-12','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (13, 'Luis', 'Sánchez', 'luis.sanchez@example.com', '678933456', '2023-07-13','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (14, 'Carmen', 'Gutiérrez', 'carmen.gutierrez@example.com', '678944567', '2023-07-14','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (15, 'Andrés', 'Castro', 'andres.castro@example.com', '678955678', '2023-07-15','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (16, 'Patricia', 'Navarro', 'patricia.navarro@example.com', '678966789', '2023-07-16','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (17, 'Fernando', 'Mendoza', 'fernando.mendoza@example.com', '678977890', '2023-07-17','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (18, 'Silvia', 'Guerra', 'silvia.guerra@example.com', '678988901', '2023-07-18','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (19, 'Raúl', 'Ortiz', 'raul.ortiz@example.com', '678999012', '2023-07-19','');
INSERT INTO usuarios (id, nombre, apellido, email, telefono, fecha_inscripcion, foto) VALUES (20, 'Elena', 'Soto', 'elena.soto@example.com', '678900123', '2023-07-20','');

